# Generated by Django 5.2.15 on 2026-06-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignatura', '0001_initial'),
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('TEORIA', 'Teoría'), ('LABORATORIO', 'Laboratorio')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_literal', models.CharField(blank=True, max_length=300)),
                ('gestion', models.PositiveSmallIntegerField(help_text='Año de la gestión, ej: 2026')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('nro_nota_adjudicacion', models.CharField(blank=True, max_length=20)),
                ('nro_informe', models.CharField(blank=True, max_length=20)),
                ('nro_memorandum', models.CharField(blank=True, max_length=20)),
                ('nro_contrato', models.CharField(blank=True, max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='asignatura.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='docente.docente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-gestion', 'docente__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADJUDICACION', 'Nota de Adjudicación'), ('INFORME', 'Informe'), ('MEMORANDUM', 'Memorándum'), ('CONTRATO', 'Contrato'), ('OTRO', 'Otro')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='contratos/documentos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contrato.contrato')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contrato',
            },
        ),
    ]
