# Generated by Django 5.2.15 on 2026-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('semestre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horas_teoria', models.PositiveSmallIntegerField(default=0)),
                ('horas_laboratorio', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, help_text='Contenido mínimo y objetivos de la asignatura')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
    ]
