# Generated by Django 5.2.15 on 2026-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('ING.', 'Ingeniero/a'), ('LIC.', 'Licenciado/a'), ('MSC.', 'Magíster Scientiarum'), ('MGS.', 'Magíster'), ('PHD.', 'Doctor en Filosofía'), ('DR.', 'Doctor'), ('CNL. DAEN', 'Coronel DAEN'), ('OTRO', 'Otro')], max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, help_text='Ej: Redes, Bases de Datos, Inteligencia Artificial', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Perfil profesional y competencias del docente')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
